<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-09-15 14:07
=======
# Generated by Django 3.0.7 on 2020-09-14 14:44
>>>>>>> b77e1374f900a7d27b55f858bad0aa0bbfac39ca

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
